# Generated by Django 5.0.2 on 2024-03-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usertogroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='max_students',
        ),
        migrations.RemoveField(
            model_name='product',
            name='min_students',
        ),
        migrations.AddField(
            model_name='group',
            name='max_students',
            field=models.IntegerField(null=True, verbose_name='Максимум человек'),
        ),
        migrations.AddField(
            model_name='group',
            name='min_students',
            field=models.IntegerField(null=True, verbose_name='Минимум человек'),
        ),
    ]
