# Generated by Django 5.0.2 on 2024-03-02 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_product_max_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='max_students',
        ),
        migrations.RemoveField(
            model_name='group',
            name='min_students',
        ),
        migrations.AddField(
            model_name='product',
            name='max_group_size',
            field=models.IntegerField(null=True, verbose_name='Минимум человек'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_group_size',
            field=models.IntegerField(null=True, verbose_name='Максимум человек'),
        ),
        migrations.CreateModel(
            name='UserToProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
    ]
