# Generated by Django 5.0.2 on 2024-03-02 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_group_max_students_remove_group_min_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='amount_students',
        ),
    ]
