# Generated by Django 5.0.2 on 2024-03-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_group_amount_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='amount_students',
            field=models.IntegerField(default=0),
        ),
    ]
