# Generated by Django 5.0.2 on 2024-03-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_group_amount_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='name_group',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='name_lesson',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name_product',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='roleofgroup',
            old_name='name_role',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='usertogroup',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='usertogroup',
            old_name='role_id',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='usertogroup',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='usertoproduct',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='usertoproduct',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='product',
            name='date_start',
            field=models.DateField(verbose_name='Дата старта продукта'),
        ),
    ]
