# Generated by Django 5.0.2 on 2024-03-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_name_group_group_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='max_group_size',
            field=models.IntegerField(null=True, verbose_name='Максимум человек'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_group_size',
            field=models.IntegerField(null=True, verbose_name='Минимум человек'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Имя автора'),
        ),
    ]
