# Generated by Django 5.0.2 on 2024-03-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_product_max_group_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='roleofgroup',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Имя'),
        ),
    ]
